<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <LangVersion>7.3</LangVersion>
    </PropertyGroup>

    <PropertyGroup>
        <CUGameDir Condition="'$(CUGameDir)' == ''">$(registry:HKEY_CURRENT_USER\Software\Valve\Steam@SteamPath)\steamapps\common\Casualties Unknown Demo</CUGameDir>
    </PropertyGroup>
    
    <ItemGroup>
        <Reference Include="BepInEx">
            <HintPath>$(CUGameDir)\BepInEx\core\BepInEx.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="0Harmony">
            <HintPath>$(CUGameDir)\BepInEx\core\0Harmony.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="UnityEngine">
            <HintPath>$(CUGameDir)\CasualtiesUnknown_Data\Managed\UnityEngine.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="UnityEngine.CoreModule">
            <HintPath>$(CUGameDir)\CasualtiesUnknown_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="Assembly-CSharp">
            <HintPath>$(CUGameDir)\CasualtiesUnknown_Data\Managed\Assembly-CSharp.dll</HintPath>
            <Private>false</Private>
        </Reference>
    </ItemGroup>

</Project>
